module.exports = {
  NODE_ENV: process.env.NODE_ENV,
  LOGGLY_ACCESS_TOKEN: process.env.LOGGLY_ACCESS_TOKEN,
  COS_AUTH_URL: process.env.COS_AUTH_URL,
  COS_PROJECT_ID: process.env.COS_PROJECT_ID,
  COS_DOMAIN_ID: process.env.COS_DOMAIN_ID,
  COS_USERNAME: process.env.COS_USERNAME,
  COS_PASSWORD: process.env.COS_PASSWORD,
  AUTH_SERVICE_DNS: process.env.AUTH_SERVICE_DNS,
  AUTH_SERVICE_ADMIN_EMAIL: process.env.AUTH_SERVICE_ADMIN_EMAIL,
  AUTH_SERVICE_ADMIN_PASSWORD: process.env.AUTH_SERVICE_ADMIN_PASSWORD
}
