apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cos-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cos-service
        tier: server
    spec:
      containers:
      - name: cos-service 
        image: registry.ng.bluemix.net/jiri/cos-service:latest 
        imagePullPolicy: Always        
        ports:
        - name: cos-service
          containerPort: 3003
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: NODE_ENV
          - name: LOGGLY_ACCESS_TOKEN
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: LOGGLY_ACCESS_TOKEN                
          - name: COS_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: COS_AUTH_URL
          - name: COS_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: COS_PROJECT_ID
          - name: COS_DOMAIN_ID
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: COS_DOMAIN_ID                
          - name: COS_USERNAME
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: COS_USERNAME
          - name: COS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: jinni-cos-service
                key: COS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cos-service-loadbalancer-service 
spec:
  selector:
    app: cos-service 
  ports:
    - protocol: TCP
      port: 80
      targetPort: cos-service 
  type: LoadBalancer

